services:
  frontend:
    build: ./frontend
    container_name: frontend
    networks:
      - appnet

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8080:8080"
    networks:
      - appnet

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
